/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactForm {
  'name' : string,
  'email' : string,
  'company' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface PartnerApplication {
  'partnerType' : string,
  'name' : string,
  'role' : string,
  'email' : string,
  'company' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface RequirementSubmission {
  'role' : string,
  'engagementType' : string,
  'company' : string,
  'timestamp' : Time,
  'skills' : string,
  'location' : string,
  'startDate' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'company' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VendorApplication {
  'contactPerson' : string,
  'email' : string,
  'timestamp' : Time,
  'technologies' : string,
  'companyName' : string,
  'phone' : string,
  'benchSize' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteContactForm' : ActorMethod<[], undefined>,
  'deletePartnerApplication' : ActorMethod<[], undefined>,
  'deleteRequirementSubmission' : ActorMethod<[], undefined>,
  'deleteVendorApplication' : ActorMethod<[], undefined>,
  'getAllContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getAllPartnerApplications' : ActorMethod<[], Array<PartnerApplication>>,
  'getAllRequirementSubmissions' : ActorMethod<
    [],
    Array<RequirementSubmission>
  >,
  'getAllVendorApplications' : ActorMethod<[], Array<VendorApplication>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'submitPartnerApplication' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'submitRequirementSubmission' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'submitVendorApplication' : ActorMethod<
    [string, string, string, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];